------A . ### Phase 1 — Exploratory Data Analysis (EDA)

------- 1.1 Explore all data in the database 


select * from INFORMATION_SCHEMA.tables

-- 1.2 explore all columsn  in the data base 
select * from INFORMATION_SCHEMA.columns
where TABLE_NAME= 'dim_customers';

------- 2. Dimension Exploration (distinct[dimensions] )

select 
distinct country 
from gold.dim_customers;  

-- 2.1 [major category 
select 
distinct category ,subcategory  ,product_name
from gold.dim_products
order by 1,2,3; 


------- 3.date exploration mix/max[date_dimension]

select min(order_date) as first_order_date,max(order_date) as last_order_date
from gold.fact_sales;
-- how many years for sales available 

select 
min(order_date) as first_order_date,
max(order_date) as last_order_date,
datediff(month,min(order_date),max(order_date)) as  order_range_months 
from gold.fact_sales;

-- yongest and oldest customers 

select 
min(birthdate) youngest_bday,
datediff(year,min(birthdate),getdate()) as old_age,
max(birthdate) oldest_bday,
datediff(year,max(birthdate),getdate()) as young_age
from gold.dim_customers;


------- 4 . Measure explaoration (agreate [measure ])

-- Find the Total Sales

select sum(sales_amount)
from gold.fact_sales;
-- Find how many items are sold

select sum(quantity) as total_quantity 
from gold.fact_sales;

-- Find the average selling price

select avg(price) 
from gold.fact_sales;

-- Find the Total number of Orders

select count(distinct order_number) as total_order
from gold.fact_sales;

-- Find the total number of products

select count(product_key) as product_count
from gold.dim_products;

select count(distinct product_key) as product_count
from gold.dim_products;

-- Find the total number of customers

select count(customer_key) as total_customers
from gold.dim_customers;

-- Find the total number of customers that has placed an order

select count(distinct customer_key) as total_customers
from gold.fact_sales;

------4.1 . REPORT FOR ALL KEY METRICS 

-- Generate a Report that shows all key metrics of the business

SELECT 'Total Sales' AS measure_name, SUM(sales_amount) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total Quantity', SUM(quantity) FROM gold.fact_sales
UNION ALL
SELECT 'Average Price', AVG(price) FROM gold.fact_sales
UNION ALL
SELECT 'Total Nr. Orders', COUNT(DISTINCT order_number) FROM gold.fact_sales
UNION ALL
SELECT 'Total Nr. Products', COUNT(product_name) FROM gold.dim_products
UNION ALL
SELECT 'Total Nr. Customers', COUNT(customer_key) FROM gold.dim_customers;


----5 Magnitude analysis (aggregate measure by [dimension])

-- Find total customers by countries
SELECT
country,
COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC

-- Find total customers by gender
SELECT
gender,
COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC

-- Find total products by category
SELECT
category,
COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC

-- What is the average costs in each category?
SELECT
category,
AVG(cost) AS avg_cost
FROM gold.dim_products
GROUP BY category
ORDER BY avg_cost DESC

-- What is the total revenue generated for each category?

select 
p.category,
sum(f.sales_amount) as total_revenue
from gold.dim_products p
left join gold.fact_sales f on p.product_key = f.product_key
where category is not null
group by category 
order by total_revenue desc;
-- Find total revenue generated by each customer
SELECT
c.customer_key,
c.first_name,
c.last_name,
SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON f.customer_key = c.customer_key
GROUP BY c.customer_key, c.first_name, c.last_name
ORDER BY total_revenue DESC

-- What is the distribution of sold items across countries?
SELECT
c.country,
SUM(f.quantity) AS total_items_sold
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON f.customer_key = c.customer_key
GROUP BY c.country
ORDER BY total_items_sold DESC



---- 6 .EDA RANKING ANALYSIS (TOP N -- BOTTOM N)

-- Which 5 products generate the highest revenue?
SELECT TOP 5
p.product_name,
SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key = f.product_key
GROUP BY p.product_name
ORDER BY total_revenue DESC

--window fuc

SELECT *
FROM (
    SELECT
    p.product_name,
    SUM(f.sales_amount) AS total_revenue,
    ROW_NUMBER() OVER (ORDER BY SUM(f.sales_amount) DESC) AS rank_products
    FROM gold.fact_sales f
    LEFT JOIN gold.dim_products p
    ON p.product_key = f.product_key
    GROUP BY p.product_name
) t
WHERE rank_products <= 5

-- What are the 5 worst-performing products in terms of sales?
SELECT top 5
p.product_name,
SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key = f.product_key
GROUP BY p.product_name
ORDER BY total_revenue ASC



